### ISSUE TITLE
Run linting task on Travis

### ISSUE THREAD

**Issue by not-an-aardvark** [eslint/website#402]
We have a linting task that lints JS files as of https://github.com/eslint/eslint.github.io/pull/393, but the task doesn't get run automatically for PRs on Travis. I'm not sure how to do this because we already have the language set to ruby in `.travis.yml` to index the site with algolia, so we would need to set up a separate build to run `npm install` and `npm test` for PRs. Someone who knows more about travis config files might be able to do this.

**Comment by platinumazure** [comment]
Found this thread/comment: https://github.com/travis-ci/travis-ci/issues/4090#issuecomment-122688955

Maybe we could just invoke nvm as part of the test script (while still using ruby as the language)?

**Comment by platinumazure** [comment]
Do we need the Travis task to be in Ruby anymore if we no longer need to call Algolia directly (since we should have switched over to DocSearch by now)?

(cc @ilyavolodin)

**Comment by kaicataldo** [comment]
I'll see if I can fix this. Travis has been failing since we turned it on (for reasons unrelated to this) and should be fixed by https://github.com/eslint/eslint.github.io/pull/578.

**Comment by snitin315** [comment]
I think we can close it since we have added a lint job workflow. - https://github.com/eslint/website/blob/master/.github/workflows/ci.yml
