### ISSUE TITLE
eslint executing on terminal  issue

### ISSUE THREAD

**Issue by sundartinesh** [eslint/website#505]
I  have written nearly 10 rules for my project and kept in the same folder.I executed each rule and store the output in a separate text file and kept in the subfolder .If I try to execute a particular rule,I got some other txt file getting printed on the terminal.If the same rule is again put in a separate folder, i can get the result.What is the exact the for that error

**Comment by Aladdin-ADD** [comment]
hi, @sundartinesh  thanks for creating the issue, I'm not sure I got your meaning.  please just provide as much additional information as possible, e.g. the command that you used to run ESLint.

also, you can join our [chatting room](https://groups.google.com/group/eslint) for more help! 😄

**Comment by kaicataldo** [comment]
Also, is this an issue with https://eslint.org/ website?
