### ISSUE TITLE
Demo default ECMAVersion should be 2018

### ISSUE THREAD

**Issue by nzakas** [eslint/website#508]
When the demo is loaded for the first time, the ECMAVersion is set to 5, so it produces errors for all of the new syntax. I think that is confusing, as the ECMAVersion setting is hidden behind a click. Let's set the default ECMAVersion to 2018.

**Comment by not-an-aardvark** [comment]
I'm wondering if it would be more confusing for the demo's default to be different from ESLint's default. Someone might be confused about why ESLint isn't parsing their code and try to figure out the issue in the demo, only to realize that the code mysteriously works in the demo.

I agree that it can be confusing when new syntax produces errors, but I think it would be better to solve that problem by changing the default in ESLint itself.

**Comment by aladdin-add** [comment]
@nzakas  is this still an issue?

**Comment by aladdin-add** [comment]
seems the default is still es5, will make a PR to fix it.
