### ISSUE TITLE
discussion: what sort of minimum versions we need to support?

### ISSUE THREAD

**Issue by aladdin-add** [eslint/website#543]
refs:https://github.com/eslint/eslint/pull/11398#discussion_r257776506
a bit related to #537

**Comment by j-f1** [comment]
@jamiebuilds’s [suggestion](https://jamie.build/last-2-versions) of `>0.25%, not ie 11, not op_mini all` is one option.

**Comment by g-plane** [comment]
We can consider creating a "modern build" like `vue-cli` does.

**Comment by aladdin-add** [comment]
> @jamiebuilds’s suggestion of >0.25%, not ie 11, not op_mini all is one option.

at the very least, we still need to support IE11, for window 7 users -- Edge requires window 10. But I'd like to see someone share the GA data.

+ https://support.microsoft.com/en-us/help/11531/internet-explorer-system-requirements
+ https://www.microsoft.com/en-us/download/details.aspx?id=48126

**Comment by g-plane** [comment]
However, the ESLint website itself doesn't use Babel currently.

**Comment by ilyavolodin** [comment]
Here's top 40 browser stats for one week (Feb 12 - 18):

| Sessions | Browser Major Version | Percentage  |
|----------|-----------------------|-------------|
| 40645    | 72 Chrome             | 0.447563151 |
| 29380    | 71 Chrome             | 0.3235184   |
| 4492     | 65 Firefox            | 0.049463739 |
| 3801     | 12 Safari             | 0.04185478  |
| 2352     | 70 Chrome             | 0.02589909  |
| 1063     | 69 Chrome             | 0.011705244 |
| 627      | 68 Chrome             | 0.006904222 |
| 591      | 63 Chrome             | 0.006507807 |
| 550      | 67 Chrome             | 0.006056335 |
| 529      | 74 Chrome             | 0.005825093 |
| 522      | 17 Edge               | 0.005748012 |
| 520      | 73 Chrome             | 0.005725989 |
| 502      | 66 Firefox            | 0.005527782 |
| 491      | 11 Internet Explorer  | 0.005406655 |
| 418      | 58 Opera              | 0.004602815 |
| 381      | 64 Firefox            | 0.004195388 |
| 297      | 57 Opera              | 0.003270421 |
| 285      | 11 Safari             | 0.003138283 |
| 268      | 60 Firefox            | 0.002951087 |
| 260      | 65 Chrome             | 0.002862995 |
| 253      | 66 Chrome             | 0.002785914 |
| 248      | 18 Edge               | 0.002730856 |
| 202      | 64 Chrome             | 0.002224327 |
| 181      | 19 YaBrowser          | 0.001993085 |
| 142      | 18 YaBrowser          | 0.001563636 |
| 111      | 16 Edge               | 0.001222279 |
| 105      | 62 Chrome             | 0.001156209 |
| 92       | 61 Chrome             | 0.00101306  |
| 88       | 63 Firefox            | 0.000969014 |
| 84       | 58 Chrome             | 0.000924968 |
| 76       | 5 Samsung Internet    | 0.000836875 |
| 75       | 52 Firefox            | 0.000825864 |
| 66       | 57 Chrome             | 0.00072676  |
| 62       | 55 Chrome             | 0.000682714 |
| 60       | 67 Firefox            | 0.000660691 |
| 57       | 61 Firefox            | 0.000627657 |
| 56       | (not Safari (in-app)  | 0.000616645 |
| 55       | 60 Chrome             | 0.000605633 |
| 45       | 56 Chrome             | 0.000495518 |
| 39       | 36 Chrome             | 0.000429449 |

P.S. I wish Google Analytics would finally add ability to get browsers by major version... This jumping through Excel hoops thing takes waaay too long.

**Comment by aladdin-add** [comment]
I think we can drop IE <= 10, but do we want to support IE 11 (given its ~0.54% share)?

**Comment by g-plane** [comment]
Can we create two builds? One is for old browsers and another is for evergreen browsers.

**Comment by ilyavolodin** [comment]
What would be the point of creating two builds? I'm fine with dropping IE10. But I would keep IE11, as it's not upgradable.

**Comment by g-plane** [comment]
For those who uses evergreen browsers, they can leverage the optimization of the new browsers and fetch smaller bundle size (less Babel transpilation).

**Comment by aladdin-add** [comment]
I'm not a big fan of this -- as Chrome takes the largest body, it seems not worthy the complexity IMHO.

**Comment by aladdin-add** [comment]
seems we got a problem on IE11. see https://github.com/eslint/eslint/issues/11504#issuecomment-473632476

I'm afraid we have to drop support it. thoughts?

**Comment by kaicataldo** [comment]
> For those who use evergreen browsers, they can leverage the optimization of the new browsers and fetch smaller bundle size (less Babel transpilation).

I'm a bit confused by this, because as far as I know we're not actually transpiling anything. Is the purpose of this discussion to decide on a policy so that going forward we can potentially start using features from ES2015 and beyond?

Some relevant discussion regarding adding a build step: https://github.com/eslint/eslint.github.io/issues/536

**Comment by aladdin-add** [comment]
> I'm a bit confused by this, because as far as I know we're not actually transpiling anything.

 I think @g-plane means eslint.js/espree.js in the demo page -- they were built in eslint repo.

**Comment by kaicataldo** [comment]
It would be nice to have some data - who here has access to the Google Analytics account?

**Comment by ilyavolodin** [comment]
I have access to google analytics. But creating those reports based on browser version is a major pain, since GA doesn't support it naively, and you have to do a huge number of transformations in Excel. What information are you looking for, specifically?

**Comment by kaicataldo** [comment]
I was wondering if it would be useful to get a breakdown of what percentage of visits are from various browsers so that we can let that inform our decision here.

**Comment by ilyavolodin** [comment]
You mean by browser or by browser version (like the table above)? By browser, it's easy, GA has a report that I can generate without any problem. By browser version takes a lot of work, since GA doesn't support that type of report naively and you have to correlate multiple reports by hands in Excel.

**Comment by kaicataldo** [comment]
@ilyavolodin Maybe we could start with the breakdown of browsers? i.e. if we see that IE is <2% of traffic maybe we can drop support. I think the tricky one here is Safari, since it doesn't automatically update and is tied to macOS versions.

**Comment by aladdin-add** [comment]
IE 11 is ~0.54%, and I didn't see IE<11 in top40. see https://github.com/eslint/eslint.github.io/issues/543#issuecomment-465231289

should this be discussed in a TSC meeting?

**Comment by g-plane** [comment]
Demo can't be run on IE now: https://github.com/eslint/eslint/issues/11504 .

**Comment by kaicataldo** [comment]
Oh, really sorry @ilyavolodin, I don’t know how I missed the breakdown above.

**Comment by ilyavolodin** [comment]
Well, that breakdown is pretty old. But it took me over an hour and a half to build it, that's why I'm hesitant to commit to redoing it again:-) But here's breakdown for top 10 browsers (not versions) for the last month:
| #   | Browser               | Users (percentage)|
|----|--------------------|---------------------|
| 1.  | Chrome                | 199,277(84.98%)  |
| 2.  | Firefox                  | 15,275(6.51%)      |
| 3.  | Safari                    | 10,228(4.36%)      |
| 4.  | Internet Explorer  | 3,636(1.55%)        |
| 5.  | Edge                     | 2,676(1.14%)        |
| 6.  | Opera                   | 1,876(0.80%)        |
| 7.  | YaBrowser             | 606(0.26%)          |
| 8.  | Samsung Internet | 316(0.13%)          |
| 9.  | Android Webview | 195(0.08%)          |
| 10. | Safari (in-app)      | 136(0.06%)          |

**Comment by aladdin-add** [comment]
just added it to tsc agenda.

please note: demo can't be run on IE now (as @g-plane mentioned), and seems there is no easy ways to fix it.

**Comment by kaicataldo** [comment]
This was discussed at this week's TSC meeting. The TSC resolved that the website will support IE 11, but that we won't support IE 11 in the demo due to it being such a small percentage of visits and doesn't seem like a trivial amount of work.

**Comment by aladdin-add** [comment]
Closing due to age.
