### ISSUE TITLE
Suggestion: add blogpost on The inception of ESLint

### ISSUE THREAD

**Issue by sw-yx** [eslint/website#568]
It is important to leave a trail for others who may be researching ESLint and writing something similar, i'd like to suggest adding @nzakas's post, either to this site or to the ESLint README (maybe under FAQ)

https://humanwhocodes.com/blog/2018/02/the-inception-of-eslint/

**Comment by thomasgilmore95** [comment]
Hi, can I take on this issue?

**Comment by aladdin-add** [comment]
sure, please feel free. :)

**Comment by nzakas** [comment]
I wouldn’t mind that, but I’d like to improve the design of the blog before doing that. Right now, we don’t have important aspects on a blog post such as author name, date, or an easy way to specify the canonical URL for the content.

**Comment by thomasgilmore95** [comment]
I am happy to help with both. I can add the author name and date to each article under the title if that works. Can I get more information regarding "an easy way to specify the canonical URL for the content". Thank you.

**Comment by nzakas** [comment]
> an easy way to specify the canonical URL for the content

Ideally, we could put “canonical_url” in the front matter of a blog post and have it both insert the meta tag and insert a notice at the top of the post saying it is being reposted with permission.

**Comment by thomasgilmore95** [comment]
I can add the author / contributors name of the blog post into the front matter of the blog post if you would still like.

**Comment by nzakas** [comment]
@thomasgilmore95 that would be great!

**Comment by thomasgilmore95** [comment]
Sounds good I will start working on this

**Comment by thomasgilmore95** [comment]
I created a pull request for this issue for the blog post authors to make sure I'm doing this the best way. Please let me know if you would like me to make changes on this before I continue with this. Thank you.

**Comment by nzakas** [comment]
Here's what the blog post will look like (feel free to make a PR including this):
https://gist.github.com/nzakas/bf6d129e4b48b27c96e9ae4dbb9b29eb

The `url` values in the frontmatter shouldn't be at the same level, so they won't conflict.

If `page.original` is present, the canonical URL should be set to `page.original.url` and otherwise it should be `page.url` (what we currently have). So something like:

```liquid
{% if page.original %} 
<link rel="canonical" href="{{ page.original.url }}">
{% else %}  
<link rel="canonical" href="{{ page.url | replace: '.html', '' }}">
{% endif %}  
```

**Comment by thomasgilmore95** [comment]
I created a PR for this. Let me know if I'm on the right track for this. Thank you.

**Comment by thomasgilmore95** [comment]
Is there anything else regarding this issue that needs to be worked on?

**Comment by nzakas** [comment]
Nope! Post is live. Thanks so much.
