### ISSUE TITLE
Can we bundle ESLint and Espree directly in this repository on build?

### ISSUE THREAD

**Issue by kaicataldo** [eslint/website#596]
We currently [bundle](https://github.com/eslint/eslint/blob/master/webpack.config.js#L6-L7) `lib/linter/linter.js` and `espree` and [copy the bundles](https://github.com/eslint/eslint/blob/master/Makefile.js#L777-L778) into this repository during the release script.

It would be nice if we could just do all the bundling directly in this repository every time we build.

Some problems to solve:
1. The publish step occurs after the site is generated, so we can't just pull and build the latest version on commit.
2. We would have to figure out how to bundle the latest releases while not changing the versions we're using to lint this repository.

Benefits:
1. `eslint/eslint` wouldn't have to worry about bundling any more
2. We can consolidate the Webpack/Babel configs in this repository.

**Comment by ilyavolodin** [comment]
The issue with that is updates to the site that happen outside of regular ESLint release schedule. In that case, we might've already merged some changes into master on ESLint/espree repositories, but haven't yet published them. Site will pull whatever is latest. If we can make it pull from the last known tag, I'd be fine with that (faster release build is always a good thing).

**Comment by kaicataldo** [comment]
Should have clarified, but that’s what I was intending above. Definitely should build with the latest published release, not what’s in master on GitHub.

**Comment by kaicataldo** [comment]
Relevant discussion here https://github.com/eslint/eslint/pull/12006#issuecomment-513076818

**Comment by platinumazure** [comment]
I would love to see if we could have a build/release step which pulls in ESLint and espree and builds them here. Additionally, this repo could be responsible for copying the documentation from the ESLint repository. This would allow ESLint to go back to a mostly standard release (i.e., wouldn't need to add much to what eslint-release already provides), and this repository can then fully "own" the logic for building and deploying the website.

**Comment by kaicataldo** [comment]
I really like that idea. We could then change our release build to do the following:

1. Clone `eslint/eslint` and `eslint/website`
1. Run the release script in `eslint/eslint`
1. Run the release script in `eslint/website`, which copies the doc files from `eslint/eslint` and generates the eslint/espree bundles and commits them so that the Netlify build can then also bundle them.

It would be nice if we could bundle eslint/espree directly into the build step bundles (since it could potentially reduce bundle size), but that would require a much more complicated build step (we'd have to specify the eslint version to bundle and clone it from GitHub directly, I think, since we don't necessarily want to update the site's ESLint version on every release).

**Comment by kaicataldo** [comment]
Would love to continue this discussion! At this point, would it be best to bring this to the TSC?

**Comment by ilyavolodin** [comment]
I don't think this requires TSC approval. I'm for trying this out. Seems like a good idea.

**Comment by nzakas** [comment]
@kaicataldo has this been addressed? It looks like there were some PRs merged related to this, so just checking.

**Comment by kaicataldo** [comment]
Ah, yes! We should be good to go here. Thanks.
