### ISSUE TITLE
Document new environments `es2017`, `es2020`

### ISSUE THREAD

**Issue by blake-regalia** [eslint/website#620]
Let's update the environments listed [here](https://eslint.org/docs/user-guide/configuring) so they reflect https://github.com/eslint/eslint/blob/master/conf/environments.js. Currently, I don't think there is any documentation including the `es2017` and `es2020` environments. It took me an hour to deduce why eslint was err'ing no-undef rule for `BigInt64Array` >_<

**Comment by platinumazure** [comment]
Hi @blake-regalia, thanks for the issue.

I believe this is now resolved with the latest release. Please confirm and close if you don't see any issues. Thanks!
