### ISSUE TITLE
Netlify issues caused by breaking change in Faraday gem

### ISSUE THREAD

**Issue by platinumazure** [eslint/website#625]
During the 6.5.0 release and site generation, we ran into Netlify deployment issues.

The root cause was this: https://community.netlify.com/t/jekyll-builds-consistently-failing-with-error-superclass-must-be-a-class-faraday-deprecatedconstant-given/3799

PR #624 worked around the issue by pinning the Faraday gem. This issue is for tracking the eventual full resolution of this issue. My assumption is that this will be resolved by a new version of the github pages gem being deployed (with code to work around the Faraday exception or a dependency pin on their side). Once that is available, we can revert #624.

**Comment by platinumazure** [comment]
Looks like this might be fixed with the [release of faraday 0.16.2](https://github.com/lostisland/faraday/releases/tag/v0.16.2).

This can be checked by writing a PR to remove the faraday line in the Gemfile and seeing if the Netlify preview builds.

**Comment by kaicataldo** [comment]
Test PR here: https://github.com/eslint/website/pull/627

**Comment by kaicataldo** [comment]
Looks like it's fixed! 🎉

**Comment by platinumazure** [comment]
Closing this as #627 has been merged. Thanks @kaicataldo for putting that PR together!
