### ISSUE TITLE
Demo: Rule select-all checkbox does not deselect all rules

### ISSUE THREAD

**Issue by platinumazure** [eslint/website#626]
Seems the select-all checkbox does not deselect all rules, after selecting all and then clicking once more. Not sure if this is something related to the recent release, or something else.

**Comment by g-plane** [comment]
I also encountered this problem.

**Comment by mdjermanovic** [comment]
The rules seem to be de facto disabled as they don't report errors anymore. It might be that React failed to update the DOM.

**Comment by platinumazure** [comment]
I've also noticed that refreshing the page (with a persistent demo link) seems to resolve the issue as well, so I think you're right about it being a React DOM update issue.

**Comment by mrseanbaines** [comment]
Looks like this is fixed in #632?

**Comment by g-plane** [comment]
Yes, it is.
