### ISSUE TITLE
Update scripts to account for Github supporters

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/website#647]
Currently our scripts are only checking OpenCollective for supporters to send twitter messages about and adding them to the site/readme. Now that ESLint org can be supported through Github, we need to update those scripts to use Github API for the same tasks as well.

**Comment by nzakas** [comment]
I took a quick look at this, and it seems like the GraphQL API isn't (yet?) returning data for sponsors. I tried using a modified version of the script I'm using to pull my personal sponsors list (which does work).

<details>
<summary>GraphQL query</summary>

```
query{
    organization(login:"eslint") {
      sponsorsListing {
        tiers(first: 100) {
          nodes {
            name
            monthlyPriceInDollars
            adminInfo {
              sponsorships(first: 100) {
                nodes {
                  sponsor {
                    avatarUrl
                    name
                    url
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

</details>

The list of sponsors should be in the `adminInfo` key, but it comes back as `null`. Do you have a contact for reporting problems?

**Comment by kaicataldo** [comment]
@ilyavolodin It looks like we do have a few sponsors.

**Comment by ilyavolodin** [comment]
Oh, they just joined today, I guess. I was playing with the GraphQL API yesterday evening and there was no sponsors yet.

**Comment by ilyavolodin** [comment]
API does return data. Here's the query:
```graphql
query {
  organization(login: "eslint") {
    sponsorshipsAsMaintainer (first: 100) {
      nodes {
        sponsor {
          name,
          login
        },
        tier {
          monthlyPriceInDollars
        }
      }
    }
  }
}
```
You can run it here: https://developer.github.com/v4/explorer/

**Comment by nzakas** [comment]
Nice! I can try updating the script next week but anyone should feel free to take this on in the meantime if the spirit moves you.

**Comment by nzakas** [comment]
Starting to work on this.
