### ISSUE TITLE
Can we remove the parser demo?

### ISSUE THREAD

**Issue by kaicataldo** [eslint/website#652]
Can we remove the parser demo and instead point people to [AST Explorer](https://astexplorer.net) in our documentation? I don’t think it’s particularly useful in its current state and AST Explorer is a much more robust tool for visualizing ASTs generated by Espree.

**Comment by g-plane** [comment]
I agree with that. Then we don't need to maintain too much of the website.

**Comment by ilyavolodin** [comment]
Parser demo has been removed, so closing this.
