### ISSUE TITLE
Site removes {{ }} message placeholders

### ISSUE THREAD

**Issue by mdjermanovic** [eslint/website#661]
`{{character}}` placeholder is not visible on the site:

https://eslint.org/docs/developer-guide/working-with-rules#suggestion-messageids

https://eslint.org/docs/developer-guide/working-with-rules#placeholders-in-suggestion-messages

It's visible on GitHub:

https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules.md#suggestion-messageids

https://github.com/eslint/eslint/blob/master/docs/developer-guide/working-with-rules.md#placeholders-in-suggestion-messages

Not familiar with the tool, but it could be that only `{{}}` without spaces has a meaning because this problem doesn't occur with `{{ identifier }}` and `{{ name }}`:

https://eslint.org/docs/developer-guide/working-with-rules#messageids

Actually, there is #312 in the list of related issues :-) This should be solved with `{% raw %}` ?

**Comment by kaicataldo** [comment]
Nice find! This does look like a similar case to the issue listed. `{{}}` denotes interpolated data in liquid, and it’s not rendering anything because that data key is returning a null value in that context. I’ll fix this ASAP tomorrow.
