### ISSUE TITLE
Fix broken links on the site

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/website#668]
I ran a local crawler on the site and here's the list of links that were broken:
```
http://localhost:8080/docs/maintainer-guide/governance links to missing page. List of links is ["http://localhost:8080/docs/maintainer-guide/contributing"]
Error 404 for http://localhost:8080/docs/maintainer-guide/contributing
http://localhost:8080/docs/6.0.0/user-guide/configuring links to missing page. List of links is ["http://localhost:8080/docs/6.0.0/rules/"]
Error 404 for http://localhost:8080/docs/6.0.0/rules/
http://localhost:8080/docs/5.0.0/developer-guide/working-with-rules links to missing page. List of links is ["http://localhost:8080/docs/5.0.0/rules/","http://localhost:8080/docs/5.0.0/rules/"]
Error 404 for http://localhost:8080/docs/5.0.0/rules/
http://localhost:8080/docs/5.0.0/user-guide/configuring links to missing page. List of links is ["http://localhost:8080/docs/5.0.0/rules/"]
http://localhost:8080/docs/4.0.0/user-guide/command-line-interface links to missing page. List of links is ["http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/","http://localhost:8080/docs/4.0.0/user-guide/formatters/"]
Error 404 for http://localhost:8080/docs/4.0.0/user-guide/formatters/
http://localhost:8080/blog/2016/02/eslint-v2.0.0-released links to missing page. List of links is ["http://localhost:8080/docs/developer-guide/code-path-analysis.html"]
Error 404 for http://localhost:8080/docs/developer-guide/code-path-analysis.html
http://localhost:8080/docs/2.0.0/developer-guide/working-with-rules links to missing page. List of links is ["http://localhost:8080/docs/2.0.0/developer-guide/code-path-analysis"]
http://localhost:8080/docs/2.0.0/developer-guide/code-path-analysis links to missing page. List of links is ["http://localhost:8080/docs/2.0.0/developer-guide/code-path-analysis/"]
Error 404 for http://localhost:8080/docs/2.0.0/developer-guide/code-path-analysis/
http://localhost:8080/blog/2015/06/eslint-0.24.0-released links to missing page. List of links is ["http://localhost:8080/blog/2015/preparing-for-1.0.0"]
Error 404 for http://localhost:8080/blog/2015/preparing-for-1.0.0
Total pages: 939. Errors found 7
```

**Comment by dotJoel** [comment]
I can look at this today, if you don't mind.
A spot check revealed some destinations are easy to figure out.

**Comment by dotJoel** [comment]
These three pages don't exist right now.
- `/docs/6.0.0/rules/`
- `/docs/5.0.0/rules/`
- `/docs/4.0.0/user-guide/formatters/`

`/3.0.0/rules/` and `/4.0.0/rules/` have an `index.liquid`  5 and 6 do not.
`user-guide/formatters/index.md` exists in 3.0.0 and 5.0.0, but not in 4.0.0.

I'm not sure what the team would like to do about this.

The remaining two have obvious fixes:
- `http://localhost:8080/docs/2.0.0/developer-guide/working-with-rules links to missing page. List of links is ["http://localhost:8080/docs/2.0.0/developer-guide/code-path-analysis"]`
  can change to /docs/2.0.0/developer-guide/code-path-analysis.html
- `http://localhost:8080/docs/maintainer-guide/governance links to missing page. List of links is ["http://localhost:8080/docs/maintainer-guide/contributing"]`
  can probably change to /docs/developer-guide/contributing

**Comment by nzakas** [comment]
Thanks for digging into that! I think you should be able to check out the version tags on the repo to find the missing files (for example, if you check out the v6.8.0, you should be able to find the missing rules index for v6).

**Comment by qwright10** [comment]
Also https://eslint.org/docs/rules/no-useless-backreference.

**Comment by kaicataldo** [comment]
@dotJoel Are you still willing to work on this?

**Comment by dotJoel** [comment]
@kaicataldo yea.. I will try to finish it up today.
I have some changes ready, but need to address broken links found by running LinkChecker myself.  Some seemed related to what I have done so far on this new pending branch.

**Comment by dotJoel** [comment]
@btmills this issue should be resolved by the two PRs. I was not using "refs" the second time to imply that there was work remaining.
I feel this issue is safe to close.
