### ISSUE TITLE
Site enhancements

### ISSUE THREAD

**Issue by ilyavolodin** [eslint/website#669]
This is a general list of things that I would like to see improved on the site, some of them are pie-in-the-sky type of enhancements, and some others will require larger discussion with the team on the approach:

* Documentation versioning
I think we should version all of the documentation for each released version and allow users to switch from one to another. While it would significantly increase size of this repo, github storage is free. So is Netlify. This would require us adding a way to switch between documentation versions and configure Algolia search to only account for latest version. My suggestion is to have eslint.org/docs/rules always point to the last release version, but also support eslint.org/docs/vX.XX.XX/rules

* Documentation for plugin rules
It would be awesome if at compile time we could pull some plugin packages from NPM and display rule documentation directly on the site. This would significantly increase plugin discovery rate for our users. I see a few problems with this: We would need to define some sort of format that plugins could follow to allow us to pull documentation. Process could be opt-in and managed by PRs in the site repo (it would be up to plugin creator to create a PR for us to start pulling their documentation from NPM). Documentation versioning might be very confusing and out of sync with plugins. Since this is automated process, we have no control over content, if somebody decides to put something that goes against our code of conduct into plugin documentation, we would only be able to catch it after it goes life on the site (might be able to mitigate this by a very visible banner on top of external documentation).

* Better dicoverability for processors
I think most of the people probably don't know that processors exist and what formats they support.

* Ability to configure rules in the demo
This has been brought up multiple times, but it's very hard to do properly.

* Ability to test plugins in the demo
Along the same lines as documentation for plugins, compile npm packages at build time for some of the plugins and enable them in the demo. Not sure how this would scale.

* Break down documentation into much smaller chunks.
Some of our global documentation is unreadable and very hard to search through, because it's one huge wall of text. For example "Configuring ESLint". I think it would be beneficial to break those very large articles into a bunch of much smaller pages and provide easy navigation between them.

* Site redesign
At this point, I really want site to be redesigned. I'm sorry, but I really dislike the changes we've made to the homepage with the random astronomy related background.

* Update demo to support suggestions and in-place auto-fixing
We introduced suggestions to ESLint but demo hasn't been update to support them. In general I think we could try to use our demo as a reference for editor integrations.

* Update developer sections and API references
Our API references are not clear at all and could be a lot more user-friendly. Maybe we can even generate API documentation from JSDoc?

**Comment by nzakas** [comment]
Given that there are no action items here, I'm closing this issue.
