### ISSUE TITLE
Node.js API anchor links are broken

### ISSUE THREAD

**Issue by reduckted** [eslint/website#671]
On the Node.JS API page, the links in the table of contents for the sub-sections are broken. For example, the link in the table of contents to the `SourceCode.splitLines()` method is:

https://eslint.org/docs/developer-guide/nodejs-api#sourcecodesplitlines

But the `id` of the element is `sourcecode-splitlines`. Clicking the "anchor" link next to the heading produces the correct URL.

Interestingly, the links work correctly when viewing the markdown file on GitHub. For example, this link goes to the correct section:

https://github.com/eslint/website/blob/master/docs/developer-guide/nodejs-api.md#sourcecodesplitlines

**Comment by easilyBaffled** [comment]
I tripped uppon this as well. Looks like is true for [docs/5.0.0](https://eslint.org/docs/5.0.0/developer-guide/nodejs-api) and [docs/6.0.0](https://eslint.org/docs/6.0.0/developer-guide/nodejs-api). This is coming directly from the [markdown file](https://raw.githubusercontent.com/eslint/website/master/docs/6.0.0/developer-guide/nodejs-api.md). It may be worth noting that the anchor link next to each section header has the correct link. 
I'm happy to put a small PR together fixing the markdown files for [5.0.0](https://raw.githubusercontent.com/eslint/website/master/docs/5.0.0/developer-guide/nodejs-api.md) and [6.0.0](https://raw.githubusercontent.com/eslint/website/master/docs/6.0.0/developer-guide/nodejs-api.md), would this required changes anywhere else in the project?

**Comment by kaicataldo** [comment]
Thanks for reporting this! These links are being generated by [AnchorJS](https://github.com/eslint/website/blob/master/src/js/main/index.js#L35), and it looks like the behavior is different from the links generated on GitHub. I wonder if we can fix it with the JS here?

Here's the markup on GitHub:
<img width="542" alt="Screen Shot 2020-01-14 at 11 21 00 AM" src="https://user-images.githubusercontent.com/7041728/72361775-08f33a00-36c0-11ea-8f2f-ee225c835a02.png">

And here's what we have on the ESLint site:

<img width="536" alt="Screen Shot 2020-01-14 at 11 21 10 AM" src="https://user-images.githubusercontent.com/7041728/72361777-098bd080-36c0-11ea-9dc5-2e191b4b302a.png">

One final note - the documentation files actually live in the eslint/eslint repo ([here](https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md) is the file that is used to generate the page reported here).

**Comment by nzakas** [comment]
This was fixed in https://github.com/eslint/eslint/commit/aea172998ec4e2af1d9186b6767c3f34428945f4
