### ISSUE TITLE
A cookie associated with a resource at http://www.netlify.com/ was set with `SameSite=None` but without `Secure`

### ISSUE THREAD

**Issue by aladdin-add** [eslint/website#694]
![image](https://user-images.githubusercontent.com/13050025/74068771-74b69180-4a37-11ea-86dd-5b17d8a7f94d.png)

refs: https://www.chromestatus.com/feature/5633521622188032.

broswer: Microsoft Edge 79.0.309.71

**Comment by nzakas** [comment]
Can you explain more about this? Were you viewing eslint.org?

Any steps to reproduce would be helpful.

**Comment by aladdin-add** [comment]
yes, it was happening when viewing https://eslint.org/. Plus, I also reproduced it on Chrome 80.0.3987.87

**Comment by nzakas** [comment]
Hmm. On my phone right now, but maybe the Netlify badge at the bottom is the culprit?

**Comment by aladdin-add** [comment]
totally agreed, as I didn't see other assets from the the domain.

**Comment by qwright10** [comment]
Any request to Netflix like has `set-cookie` headers which don't happen to contain a SameSite attribute. This isn't an issue with the website itself and **will not** prevent the website from working.
