### ISSUE TITLE
no-sequence rule documentation is not correct

### ISSUE THREAD

**Issue by seansd** [eslint/website#695]
The first phrase literally says "Disallow Use of the Comma Operator", but that's not quite correct.
The docs correctly call out cases of usage in a `for` loop or when wrapped in parenthesis are still allowed. 

However they completely miss that any variable initialization sequences with the comma operator are also allowed.  These include:

`var x = 10, y = 20, z = 0;`
`const x = 10, y = 20;`

Suggest adding that information do the Rule details section in the documetnation.

**Comment by kaicataldo** [comment]
PRs are always welcome!

The documentation actually lives in https://github.com/eslint/eslint and gets copied into this repo when we run a release. Do you mind making an issue or PR there?

Seems like it would be informative to include multiple assignments in one statement as always valid, since this is an exception to the rule due to the way operator precedence works in JavaScript.

**Comment by kaicataldo** [comment]
I found a bug while looking into this and ended up making a PR. https://github.com/eslint/eslint/pull/12908

Please feel free to review it to make sure your concerns have been addressed!

**Comment by mdjermanovic** [comment]
> However they completely miss that any variable initialization sequences with the comma operator are also allowed. These include:
> 
> `var x = 10, y = 20, z = 0;`
> `const x = 10, y = 20;`
> 

This isn't comma operator, it's comma character in declaration syntax.

**Comment by kaicataldo** [comment]
> This isn't comma operator, it's comma character in declaration syntax.

I've been trying to figure out if this is actually considered a comma operator or not - got a link to any reading on the subject?

Regardless, I think it's fine for the docs to list the above as correct code since it provides clarity.

**Comment by mdjermanovic** [comment]
`,` and `=` characters are used directly in [Declarations and the Variable Statement](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-declarations-and-the-variable-statement) and [Initializer](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-Initializer) definitions, thus I believe they are not [Comma Operator](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-comma-operator) and [Assignment Operator](https://www.ecma-international.org/ecma-262/10.0/index.html#sec-assignment-operators) in that context.

Also, `x = 10` and `x = 10, y = 20` in `const x = 10, y = 20;` are not expressions. At least I think so :)

**Comment by kaicataldo** [comment]
That makes sense to me, though I'm curious if [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator) is incorrect then when it states that:

> Note that the comma operators in assignments may appear not to have the normal effect of comma operators because they don't exist within an expression. ... This is due to operator precedence and associativity.

Seems like the author of those docs considers the comma an operator.

> Also, x = 10 and x = 10, y = 20 in const x = 10, y = 20; are not expressions. At least I think so :)

Agreed that `const x = 10, y = 20;` is a statement, but it looks like `x = 10` and `x = 10, y = 20` are valid expressions and can be used as values:

```js
let valid = (x = 10, y = 20);
console.log(valid); // prints out `20`

let alsoValid = (x = 10);
console.log(alsoValid); // prints out `10`
```

Thanks for exploring this with me!

**Comment by mdjermanovic** [comment]
> Note that the comma operators in assignments may appear not to have the normal effect of comma operators because they don't exist within an expression. ... This is due to operator precedence and associativity.

I think they want to point out that `,` has lower precedence than `=`, so when someone wants to use `,` to trigger some side effects before assigning a value, they must use `()`:

```js
// intended behavior
f();
x = g();

// wrong
x = f(), g();

// good
x = (f(), g());
```

That's probably the meaning of "they don't exist within an expression" (unless parenthesized).

I'm not sure what would be the "normal effect of comma operators", because comma has the lowest precedence.

**Comment by mdjermanovic** [comment]
Got it now, they consider `,` in `const x = 10, y = 20;` to be an operator, and the "normal effect" is that this isn't equivalent to:

```js
const x = 10;
y = 20;
```

it's equivalent to `const` applied to both "operands":

```js
const x = 10;
const y = 20;
```

This makes sense as an explanation to avoid common mistakes, but I still think it's a wrong terminology.

I believe this is correct:

```js
// no operators
const x = 10, y = 20; 

// first "=" isn't operator, remaining two "=" and "," are operators.
let valid = (x = 10, y = 20);
```

**Comment by mdjermanovic** [comment]
> > Also, x = 10 and x = 10, y = 20 in const x = 10, y = 20; are not expressions. At least I think so :)
> 
> Agreed that `const x = 10, y = 20;` is a statement, but it looks like `x = 10` and `x = 10, y = 20` are valid expressions and can be used as values:
> 
> ```js
> let valid = (x = 10, y = 20);
> console.log(valid); // prints out `20`
> 
> let alsoValid = (x = 10);
> console.log(alsoValid); // prints out `10`
> ```

`x = 10` and `x = 10, y = 20` are expressions in this context, but within `const x = 10, y = 20;` I think the only expressions are `10` and `20` as primary expressions.

> Regardless, I think it's fine for the docs to list the above as correct code since it provides clarity.

That would be great as someone might expect that `no-sequences` also disallows multiple variable declarations in a single statement.

Side note, it can be disallowed with the [one-var](https://eslint.org/docs/rules/one-var)  rule, option `"never"`.
