### ISSUE TITLE
All Node and CommonJS rules deprecated

### ISSUE THREAD

**Issue by sidntrivedi012** [eslint/website#715]
Hey all,

First of all thanks a lot for maintaining ESLint. It is really helpful and useful. 💯 

Just wanted to ask that since all the Node and CommonJS issues show `deprecated : true` in their rules source, so are they going to be replaced by any set of new issues or is there any other workaround to use them?

Thanks 🙂

**Comment by aladdin-add** [comment]
hi, these rules have been included in `eslint-plugin-node`, please give it a try!

**Comment by sidntrivedi012** [comment]
Oh, will try it out for sure. Thanks :)
