### ISSUE TITLE
Broken table of contents links in Node.js API docs

### ISSUE THREAD

**Issue by jooohhn** [eslint/website#739]
The `ESLint`-related links in the [Node.js API](https://eslint.org/docs/developer-guide/nodejs-api) table of contents are broken. 

Problems:
- Don't jump to the correct section within the page
  - constructor() -> static static getErrorResults()
- Lead to a 404
  - LintResult type -> Formatter type

![image](https://user-images.githubusercontent.com/15751908/84453491-c3a24c80-ac0c-11ea-9cf4-637160fc1380.png)

**Comment by kaicataldo** [comment]
Thanks, I have verified this bug. A PR to fix this would be welcome! For whoever ends up working on this, the file that needs to be changed is [here](https://github.com/eslint/eslint/blob/master/docs/developer-guide/nodejs-api.md). We copy this file over to this repository when we run a release.

**Comment by jooohhn** [comment]
I created a PR for this fix in the main repo (https://github.com/eslint/eslint/pull/13415)

**Comment by kaicataldo** [comment]
Thank you!

**Comment by bradzacher** [comment]
This is a weird problem.
I've noticed that a recent change to the website has completely changed all of your anchors.

For example, your anchors for the rules page used to be just the title. Now there seems to be a number appended to the anchor:

Eg, previous link:
https://eslint.org/docs/rules/comma-dangle#options
New link:
https://eslint.org/docs/rules/comma-dangle#options-14

This is likely the same underlying cause as what has broken this table of contents.

**Comment by mdjermanovic** [comment]
This is fixed now, so closing.
