### ISSUE TITLE
Search box linking problem

### ISSUE THREAD

**Issue by nzakas** [eslint/website#747]
The search box on the website seems to only ever link to `#top` no matter where in the page the search result is located. It used to link directly to the headings you clicked on in the search results. This is a poor user experience because many of our documentation pages are quite long.

I've contacted support to see if we can get it resolved.

**Comment by nzakas** [comment]
It turns out this is caused by us. For some reason, we are not generating IDs for our headings and so the search is not picking them up. I suspect this happened when we migrated from Jekyll to Eleventy.

**Comment by kaicataldo** [comment]
@nzakas By IDs do you mean `id` attributes on the heading elements?

**Comment by mdjermanovic** [comment]
We're adding id attributes to [these headings](https://github.com/eslint/website/blob/cd5de143646f130b5805efd19560ffd36ef2f20d/src/js/main/index.js#L37) on `DOMContentLoaded`, and the search seems to be working fine with them (for example, type "suggestions" in the search).

**Comment by nzakas** [comment]
@kaicataldo yes. Jekyll was adding these automatically for us. We are now relying solely on JavaScript to assign IDs, which is why this is breaking.

**Comment by nzakas** [comment]
Working on this.
