### ISSUE TITLE
appended IDs on anchor hashes

### ISSUE THREAD

**Issue by bradzacher** [eslint/website#772]
I believe the following is a side-effect of https://github.com/eslint/website/pull/755 (filed as a separate issue as requested).

The site is now somewhat unpredictable to link to programmatically.

Previously, linking to `https://eslint.org/docs/rules/<rule-name>#options` would link to, and auto scroll to the options section for any given rule.

However now it doesn't work. This is because now anchor hash has a unique ID appended to it.
This means that for a given rule, the options anchor will have a different ID appended, eg:
- https://eslint.org/docs/rules/comma-dangle#options-14
- https://eslint.org/docs/rules/indent#options-43
- https://eslint.org/docs/rules/no-unused-vars#options-116

This has broken all existing links to ESLint docs that people had around the web.
It's not a _huge_ deal, because it still opens the correct page, however it is a weird behaviour.

An important question that arises from this behaviour is this: are these appended IDs guaranteed to be stable forever? I.e. if someone adds a new page to the site (like a new rule doc, or even just a new heading somewhere), will that cause:
1) all the IDs to change?
2) some of the IDs to change?
3) none of the IDs to change?

If the situation was anything but (3), then this would be a pretty big regression, as it would make it impossible for anyone to create a stable link to the ESLint docs.

**Comment by mdjermanovic** [comment]
#782 should remove all unnecessary `-1`, `-2`, `-3`, ...

This doesn't entirely revert to previous header IDs, because in #755 we also changed the algorithm (from  AnchorJS's [urlify](https://github.com/bryanbraun/anchorjs/blob/261c6d3e5013cc82a7682e427378f1dd89d8456d/anchor.js#L234), to [github-slugger](https://github.com/Flet/github-slugger) + [our custom code](https://github.com/eslint/website/blob/702d0f9bb2628c3e6f9e424f01d46f7aa549e42f/_11ty/plugins/markdown-plugins.js#L34)).

However, I believe the vast majority of header IDs will be exactly the same as before #755.

**Comment by bradzacher** [comment]
I don't personally have an issue with having the IDs. It's a little bit weird to see them in the URL, but 🤷‍♂️ (chrome is moving to hiding every but the domain, so that matters less)

The big question for me is the last one I posed:
**Are the anchor IDs stable?***

For example; if I add a new rule called `aardvark-lint-rule` (because it will be alphabetically first) will that cause every single lint rule's `#options` to get a new ID?
Or will the existing IDs all remain stable, and this new page will get the new ID?

If it's the latter, then that's a problem: anchor permalinks are no longer permanent.

**Comment by mdjermanovic** [comment]
> For example; if I add a new rule called `aardvark-lint-rule` (because it will be alphabetically first) will that cause every single lint rule's `#options` to get a new ID?
> Or will the existing IDs all remain stable, and this new page will get the new ID?

It would be very unstable. I just tried this with the actual version: the new document got `id="options-1"`  and the old documents had `-number` suffixes incremented by 1.

We don't actually need `-number` suffixes, so it's fine to remove them unless there are duplicates on the same page.

I don't think we'll be able to guarantee permanent links (for example, if we add another header with the same name on the same page, the old one could be incremented by 1), but normally they shouldn't change.

**Comment by shobhitchittora** [comment]
Hi all! I can take a look at this to fix this issue. Let me know if that'd be okay. So from what I understand it'd be okay to remove the auto-increment suffixes from the headers. 

Does it have to do anything with search on Algolia? Would it be impacted ?

**Comment by mdjermanovic** [comment]
Hi @shobhitchittora, thanks for the help!

We already have PR #782 to remove the suffixes where there are not necessary. If it doesn't look good, we can consider another approach.

The search will be affected (links will point to non-existing IDs) for a short period of time until it updates the index with new IDs.
