### ISSUE TITLE
Using Icons insted of text-links

### ISSUE THREAD

**Issue by Pratyush-Saxena** [eslint/website#781]
I guess icons will look pretty much better than text-links...
![eslint](https://user-images.githubusercontent.com/52444607/92443600-5b451600-f1cf-11ea-9bae-66a87d872543.png)

**Comment by nzakas** [comment]
Thanks for the suggestion. Are you volunteering to make this change?

**Comment by Pratyush-Saxena** [comment]
Yes @nzakas ....why not

**Comment by nzakas** [comment]
Awesome, we are happy to have the help! Hopefully the setup instructions are clear enough, but let us know if you need any help getting started.

**Comment by Pratyush-Saxena** [comment]
@nzakas ....I have created a PR ... #783 .....Pls Have a look and let me know if u want any changes

**Comment by Pratyush-Saxena** [comment]
@nzakas ....I have created PR .... #783 ...Pls have a look and let me know if u want any changes
