### ISSUE TITLE
Example for linter.defineParser uses old "parse" API

### ISSUE THREAD

**Issue by cschuller** [eslint/website#785]
The code example in the documentation for eslint.defineParser at
https://eslint.org/docs/developer-guide/nodejs-api#linterdefineparser

uses the old "parse" API. 

Change to "parseForESLint" to reflect latest ESLint API.

Yes, I am happy to provide a PR.

**Comment by nzakas** [comment]
Thanks. As mentioned in the PR, parse() is still applicable and parseForESLint() is only there for when people want to provide additional functionality that is specific to Eslint.
