### ISSUE TITLE
More documentation on conflicting fixes

### ISSUE THREAD

**Issue by RunDevelopment** [eslint/website#791]
I'm writing a plugin and many of my rules create fixes with potentially overlapping text ranges (I use `replaceTextRange`). So I have conflicts. The problem here is that the (code) output depends on how these conflicts are resolved, so I need information on that.

Right now, the [documentation](https://eslint.org/docs/developer-guide/working-with-rules) on conflicts states:

> Note that a fix is not immediately applied, and may not be applied at all if there are conflicts with other fixes.

> Fixes that are unnecessarily large could conflict with other fixes, and prevent them from being applied.

That's too little to work with. When do fixes conflict? If fixes conflict which one will be applied? 
In my case, I would like certain fixes to have priority over others. Is this possible and if yes, how?

Is there any behavior in how conflicting fixes are resolved __that I can rely on__? I looked at the source code and [this is how fixes are sorted](https://github.com/eslint/eslint/blob/51674a4113a1ca877094606bbf4938ab06cc1aad/lib/linter/source-code-fixer.js#L121). I could use that behavior but I also know very well that I can't rely on it unless it is part of the documentation.

---

An example of conflicts:

My plugin (among other things) tries to simplify regex literals. One rule tries to remove __unnecessary__ groups (let's call it _Remove Groups_) and another tries to merge one-character alternatives into a character class (let's call it _Merge Characters_). These two rules can conflict in some cases:

Example: `/a|b|(?:c)|d/`

Here, _Remove Groups_ wants to replace `(?:c)` with `c` and _Merge Characters_ wants to replace `a|b|(?:c)|d` with `[abd]|(?:c)`. This creates a conflict and depending on which rule gets applied first, the final output differs.

1. If _Remove Groups_ gets applied, we'll get `/a|b|c|d/` after the first pass, and _Merge Characters_ will change this to `/[abcd]/` in the second pass. 
   Output: `/[abcd]/`
2. If _Merge Characters_ get applied, we'll get `/[abd]|(?:c)/` after the first pass. _Remove Groups_ will simplify this to `/[abd]|c/` in the second pass and, in the third pass, _Merge Characters_ will simplify this further to `/[abdc]/`. 
   Output: `/[abdc]/`

(The order of the characters in the character class is different!) 

While both outputs are correct JS code, I want ESLint to apply the fix of _Remove Groups_ first. Unfortunately, ESLint always chooses to apply the fix of _Merge Characters_ first instead because of how the fixes are sorted.

**Comment by nzakas** [comment]
Conflicting fixes are fixes that would be applied to the same part of a string. So if two fixes want to modify characters 0 through 5, only one will be applied. The best way to mitigate the risk is to make edits as small as you can. 

Keep in mind that fixes are explicitly not guaranteed to occur. We make our best effort to apply all fixes but we can also bail out to ensure correctness of the code.

**Comment by RunDevelopment** [comment]
> Conflicting fixes are fixes that would be applied to the same part of a string. So if two fixes want to modify characters 0 through 5, only one will be applied.

Maybe "Conflicting fixes are fixes that would be applied to overlapping parts of a string" is more precise?

> The best way to mitigate the risk is to make edits as small as you can.

Unfortunately, this isn't always an option. Here's an example:

Regexes again. Let's say we have a rule 1 that removes the `i` flag of a regex literal if removing the `i` flag doesn't change the meaning of the pattern. Another rule 2 will check all character classes and tries to simplify the character class using the `i` flag.

For the regex `/[aA]/i`, rule 1 wants to remove the `i` flag and rule 2 want to simplify `[aA]` to just `a`. In isolation, both edits are valid but together they will create the regex `/a/` which is incorrect (`/a/` != `/[aA]/` == `/a/i` == `/[aA]/i`).

This problem can only be solved via conflicts. In this case, rule 1 (the one that attempts to remove the flag) must modify the whole range of the regex and not just the flags (so instead of removing the flag (`"i"` -> `""`) it will replace the whole literals with the same literal but without the flag (`"/[aA]/i"` -> `"/[aA]/"`)). The resulting conflict ensures that either the flag is removed or it is used to simplify the expression.

However, while the conflict ensures correctness, it doesn't mean that the resulting code is optimal. I would really like to have some control as to which edit is chosen should a conflict occur.

> Keep in mind that fixes are explicitly not guaranteed to occur. We make our best effort to apply all fixes but we can also bail out to ensure correctness of the code.

Maybe I could use this? Is there any way to say: "If any fixes from rule X were reported, then do not apply the fixes from rule Y." That will also solve my issue without making any new guarantees for conflicts. This basically makes it possible to resolve conflicts on a rule level.

**Comment by nzakas** [comment]
> "If any fixes from rule X were reported, then do not apply the fixes from rule Y." 

This isn’t possible. Rules are intentionally isolated from each other to avoid side effects like this. 

Just FYI: if you’d like to propose doc changes, those go in the main eslint/eslint repo. The docs in that repo are copied here during a release.

**Comment by RunDevelopment** [comment]
> Just FYI: if you’d like to propose doc changes, those go in the main eslint/eslint repo.

Thank you for the information. I'll make an issue there.

> > "If any fixes from rule X were reported, then do not apply the fixes from rule Y."
> 
> [...] Rules are intentionally isolated from each other to avoid side effects like this.

May I ask how this goes against the isolation of rules? All rules would still be executed as they are now - unknowing of other rules. The only difference is that ESLint may choose to not apply certain fixes (all of this happens after all rules were executed). The ordering information could be stored as part of configs, so rules remain completely isolated.

While it's true that it could be considered a side effect that the presence of certain rules causes the fixes of others to not be applied, we do have that exact situation with conflicts anyway.
