### ISSUE TITLE
Add date posted for blog posts

### ISSUE THREAD

**Issue by TimvdLippe** [eslint/website#833]
Linked in one of the ESLint issues I found the following blog post: https://eslint.org/blog/2020/05/changes-to-rules-policies However, I wasn't able to determine on which date the blog post was published. Eventually I figured out that the full blog page shows all dates: https://eslint.org/blog/

Could you add the "date published" to a specific blog post page, to be able to determine how old a particular blog post is?

**Comment by mdjermanovic** [comment]
Makes sense to me :+1:

**Comment by nzakas** [comment]
Honestly, the reason we don’t have dates (or authors) is because I was too lazy to design that area when I launched the website. It’s always been in the back of my mind to get back to. If someone wants to take a stab at it, I’m all for it.

**Comment by snitin315** [comment]
I will add it 👍🏻

**Comment by thomasgilmore95** [comment]
Hey! I'm not sure if this issue is still open. I would like to help if it is.

**Comment by nzakas** [comment]
Still open and still looking for help!

**Comment by thomasgilmore95** [comment]
Ok, I will start working on.

**Comment by thomasgilmore95** [comment]
I created a pull request for this. Not sure if I need to do anything else for licence/cla to pass. Let me know what you think about the dates thank you.

**Comment by nzakas** [comment]
Sorry about that. We changed CLA bots and the old one creeps up periodically.

**Comment by thomasgilmore95** [comment]
All good, thank you for letting me know.
