### ISSUE TITLE
Docs: Add emoji and notice to indicate which rules provide suggestions

### ISSUE THREAD

**Issue by bmish** [eslint/website#859]
A number of core ESLint rules can provide automated suggestions. I would like to update the ESLint website (rules list and individual rule docs) to indicate which rules provide these suggestions.

* Add a 💡 emoji (represents idea/suggestion) next to rules that provide suggestions in the rules list/table
* Add the following to the top of individual rule docs:
  * 💡 Some problems reported by this rule are manually fixable by editor [suggestions](https://eslint.org/docs/developer-guide/working-with-rules#providing-suggestions).

Benefits of this change:

* Similar to how it's useful to know which rules have an autofixer, it's also useful to know which rules provide suggestions, as such functionality can enable easier adoption and usage of a rule
* Mentioning suggestions can help increase awareness of the relatively-new suggestions feature that was only released in [2019-11](https://eslint.org/blog/2019/11/eslint-v6.7.0-released) -- encouraging greater usage of it and the addition of suggestions to more rules

A number of plugins I work on have already added the suggestion emoji/notice to their rules table and individual rule docs:
* https://github.com/not-an-aardvark/eslint-plugin-eslint-plugin#supported-rules
* https://github.com/platinumazure/eslint-plugin-qunit#rules
* https://github.com/sindresorhus/eslint-plugin-unicorn#rules
* https://github.com/ember-cli/eslint-plugin-ember#components
* https://github.com/ember-template-lint/ember-template-lint#rules

And in fact, enabling plugins to reliably show the above emoji/notice is one of the reasons why I pushed for requiring rules with suggestions to enable `meta.hasSuggestions` for us to key off of (https://github.com/eslint/eslint/pull/14573).

**Comment by nzakas** [comment]
Seems reasonable. FYI, you don’t need to open an issue for this sort of thing. Just opening a PR is fine. The most likely feedback is “can I see a screenshot?” so doing the PR with the change so we can see the deploy preview helps make the case.
