### ISSUE TITLE
Make sure every blog post has a teaser

### ISSUE THREAD

**Issue by snitin315** [eslint/website#903]
From https://github.com/eslint/website/issues/894

> The teaser is 1-3 sentences that hint at the topic of the post. This is what will be shown in a list of blog posts on the new site. For that reason, we need to make sure each post has an appropriate teaser. In some cases, the teaser can just be the first paragraph of a post (especially for older release notes) but otherwise should just be a summary of the post.

Following posts doesn't have `teaser` property - 

- [ ] `_posts/2021-12-01-contra-gold-sponsor-eslint.md`
- [ ] `_posts/2021-02-18-nx-gold-sponsor-eslint.md`
- [ ] `_posts/2021-01-13-chrome-gold-sponsor-eslint.md`
- [ ] `_posts/2020-12-10-automattic-platinum-sponsor-eslint.md`
- [ ] `_posts/2020-10-07-year-paying-contributors-review.md`
- [ ] `_posts/2020-09-16-supporting-eslint-dependencies.md`
- [ ] `_posts/2020-08-19-eslint-google-season-of-docs-project-writer.md`
- [ ] `_posts/2020-08-13-microsoft-donates-10000-to-eslint.md`
- [ ] `_posts/2020-08-06-salesforce-donates-10000-to-eslint.md`
- [ ] `_posts/2019-11-07-funding-update.md`
- [ ] `_posts/2019-09-09-indeed-donates-10000-to-eslint.md`
- [ ] `_posts/2019-05-01-funding-update.md`
- [ ] `_posts/2019-02-12-funding-eslint-future.md`
- [ ] `_posts/2019-01-18-future-typescript-eslint.md`
- [ ] `_posts/2018-07-12-postmortem-for-malicious-package-publishes.md`
- [ ] `_posts/2016-07-15-jscs-end-of-life.md`
- [ ] `_posts/2016-04-19-eslint-joins-the-jquery-foundation.md`
- [ ] `_posts/2014-12-24-espree-esprima.md`

**Comment by nzakas** [comment]
Thanks for catching that!

**Comment by AkashaRojee** [comment]
Hello!

Is this issue available to work on, please? If yes, I would like to do this.

**Comment by nzakas** [comment]
Yes it is! We still aren’t sure which posts have teasers and which don’t, so we would appreciate the help.

**Comment by AkashaRojee** [comment]
Great! I'll take it :)

**Comment by AkashaRojee** [comment]
Hello!

I'd just like to share some updates.

- Work is happening [here](https://github.com/AkashaRojee/eslint-website/tree/903-add-teasers)

- Found other posts without teasers

  - `_posts/2020-08-28-eslint-public-roadmap.md`
  - `_posts/2020-08-10-making-eslint-more-inclusive.md`
  - `_posts/2016-07-01-eslint-new-rule-format.md`
  - `_posts/2014-11-15-es6-jsx-support.md`

- Completed: posts up to 2019 inclusive

- Left to do: 2020 and 2021 posts

I am planning to finish them this week.

**Comment by nzakas** [comment]
Nice! Feel free to submit a PR as you finish each year rather than waiting for it all.

**Comment by AkashaRojee** [comment]
Sorry for the delay. Everything is complete now, so I submitted one PR. Please, let me know if there's any changes required, though.

Thanks!
