### ISSUE TITLE
Search results are not scrollable

### ISSUE THREAD

**Issue by sorokinvj** [eslint/website#908]
Hey guys, 

Search is impossible to use if you can't see all the results. Consider this:

![Jan-24-2022 14-41-34](https://user-images.githubusercontent.com/4914235/150803826-40fbc29f-5559-45a3-b2a9-164e7a267a41.gif)

I think `body` should have `overflow: hidden` with every modal opened.

**Comment by nzakas** [comment]
We're using the default Algolia search component, so unfortunately we don't have a lot of control over that. It's something we're looking to improve in the new site but won't be spending any time for the current one.
