### ISSUE TITLE
Authors not displayed on blog posts with more than 1 author

### ISSUE THREAD

**Issue by AkashaRojee** [eslint/website#913]
On blog posts with more than 1 author, the authors aren't displayed, only one GitHub URL is generated, and the URL is also incorrect.

For e.g. the post [Making ESLint more inclusive](https://github.com/eslint/website/blob/master/_posts/2020-08-10-making-eslint-more-inclusive.md) has authors `nzakas` and `kaicataldo`, but nothing is displayed after "by", and the generated GitHub URL is `https://github.com/nzakas,kaicataldo`.

![image](https://user-images.githubusercontent.com/81232315/151874908-bfddf0bf-dcb7-419a-bad9-273746bce87c.png)

I found the error in the code causing this.

https://github.com/eslint/website/blob/ed5a6205d9a277bb9cc51956065d0b204baecc9f/_layouts/post.liquid#L20

should be

```
{% assign members = authors | split: "," %}
```

I have tried it out [here](https://github.com/AkashaRojee/eslint-website/tree/fix-authors) on my fork.

Let me know if I can go ahead and submit a PR for this issue.

Thanks!

**Comment by mdjermanovic** [comment]
Hi @AkashaRojee,

Thanks for finding this error, a PR is welcome!

**Comment by AkashaRojee** [comment]
Hi @mdjermanovic,

Great, I'm on it!
