### ISSUE TITLE
Fix blog post authors

### ISSUE THREAD

**Issue by nzakas** [eslint/website#918]
I've been reviewing the authors listed on various blog posts, and in general, all of the posts with multiple authors listed are incorrect. It looks like people who simply contributed commits to a release are now listed as an author on the blog post, which is pretty confusing.

We need to go through and update every post with multiple authors to eliminate all but the first author that is listed. That will give us the correct info about who actually wrote the post.

For instance, if the front matter has this:

```
authors:
- nzakas
- btmills
- mdjermanovic
```

Then it should be changed to:

```
authors:
- nzakas
```

**Comment by AkashaRojee** [comment]
Happy to take this :)

**Comment by nzakas** [comment]
Thank you 🙏
