### ISSUE TITLE
Please provide documentation in yml format as well

### ISSUE THREAD

**Issue by AncientSwordRage** [eslint/website#926]
Currently the web page only shows documentation as a JSON object:
```
{
    "comma-dangle": ["error", "never"],
    // or
    "comma-dangle": ["error", {
        "arrays": "never",
        "objects": "never",
        "imports": "never",
        "exports": "never",
        "functions": "never"
    }]
}
```

But I'm moving towards using yaml more, so I've started a project with .eslintrc.yml and I'm having to mentally convert between JSON and yaml, or reading these: https://gist.github.com/alefteris/39c9cfe3a6baa9fc5acf

But now I have LintLens installed in vscode, I'm realising there's not even an option to switch between formats on the website.

**Comment by nzakas** [comment]
We are actually moving away from YAML as a configuration format, so we won’t be adding any more documentation about it. Sorry for the inconvenience.
